### ISSUE TITLE
MissingObjectException kills Repository viewer activity

### ISSUE THREAD

**Issue by rtyley** [rtyley/agit#16]
E/AndroidRuntime( 1129): FATAL EXCEPTION: main
E/AndroidRuntime( 1129): java.lang.RuntimeException: org.eclipse.jgit.errors.MissingObjectException: Missing unknown d65b27810bb8052fb8db705dcd88769a64512ab1
E/AndroidRuntime( 1129):    at com.madgag.agit.RDTBranch$1.apply(RDTBranch.java:69)
E/AndroidRuntime( 1129):    at com.madgag.agit.RDTBranch$1.apply(RDTBranch.java:63)
E/AndroidRuntime( 1129):    at com.google.common.collect.Iterators$8.next(Iterators.java:765)
E/AndroidRuntime( 1129):    at com.google.common.collect.Lists.newArrayList(Lists.java:139)
E/AndroidRuntime( 1129):    at com.google.common.collect.Lists.newArrayList(Lists.java:119)
E/AndroidRuntime( 1129):    at com.madgag.agit.RDTBranch.getAll(RDTBranch.java:63)
E/AndroidRuntime( 1129):    at com.madgag.agit.RepoDomainType.summariseAll(RepoDomainType.java:67)
E/AndroidRuntime( 1129):    at com.madgag.agit.RDTypeViewHolder.updateViewFor(RDTypeViewHolder.java:17)
E/AndroidRuntime( 1129):    at com.madgag.agit.RDTypeViewHolder.updateViewFor(RDTypeViewHolder.java:7)
E/AndroidRuntime( 1129):    at com.madgag.android.listviews.ViewHoldingListAdapter.getView(ViewHoldingListAdapter.java:70)
E/AndroidRuntime( 1129):    at android.widget.AbsListView.obtainView(AbsListView.java:1446)
E/AndroidRuntime( 1129):    at android.widget.ListView.measureHeightOfChildren(ListView.java:1216)
E/AndroidRuntime( 1129):    at android.widget.ListView.onMeasure(ListView.java:1127)
E/AndroidRuntime( 1129):    at android.view.View.measure(View.java:8330)
E/AndroidRuntime( 1129):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
E/AndroidRuntime( 1129):    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1017)
E/AndroidRuntime( 1129):    at android.widget.LinearLayout.measureVertical(LinearLayout.java:386)
E/AndroidRuntime( 1129):    at android.widget.LinearLayout.onMeasure(LinearLayout.java:309)
E/AndroidRuntime( 1129):    at android.view.View.measure(View.java:8330)
E/AndroidRuntime( 1129):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
E/AndroidRuntime( 1129):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
E/AndroidRuntime( 1129):    at android.view.View.measure(View.java:8330)
E/AndroidRuntime( 1129):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
E/AndroidRuntime( 1129):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
E/AndroidRuntime( 1129):    at android.view.View.measure(View.java:8330)
E/AndroidRuntime( 1129):    at android.view.ViewRoot.performTraversals(ViewRoot.java:839)
E/AndroidRuntime( 1129):    at android.view.ViewRoot.handleMessage(ViewRoot.java:1860)
E/AndroidRuntime( 1129):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 1129):    at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime( 1129):    at android.app.ActivityThread.main(ActivityThread.java:3835)
E/AndroidRuntime( 1129):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1129):    at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime( 1129):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
E/AndroidRuntime( 1129):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
E/AndroidRuntime( 1129):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 1129): Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing unknown d65b27810bb8052fb8db705dcd88769a64512ab1
E/AndroidRuntime( 1129):    at org.eclipse.jgit.storage.file.WindowCursor.open(WindowCursor.java:125)
E/AndroidRuntime( 1129):    at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:228)
E/AndroidRuntime( 1129):    at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:811)
E/AndroidRuntime( 1129):    at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:724)
E/AndroidRuntime( 1129):    at com.madgag.agit.RDTBranch$1.apply(RDTBranch.java:66)
E/AndroidRuntime( 1129):    ... 34 more
W/ActivityManager(  233):   Force finishing activity com.madgag.agit/.RepositoryManagementActivity

**Comment by rtyley** [comment]
I'm not sure how I managed to do a clone and get a repo in this state - when I re-cloned from the same remote it was fine.

**Comment by rtyley** [comment]
A slightly different death:

E/AndroidRuntime( 2886): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.madgag.agit/com.madgag.agit.RepositoryViewerActivity}: com.google.inject.ProvisionException: Guice provision errors:
E/AndroidRuntime( 2886): 
E/AndroidRuntime( 2886): 1) Error injecting constructor, java.lang.RuntimeException: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 6cb8bc92e0ca524a76a6fa3f6814b43ea9a3b30d
E/AndroidRuntime( 2886):   at com.madgag.agit.RepoSummary.<init>(Unknown Source)
E/AndroidRuntime( 2886):   while locating com.madgag.agit.RepoSummary
E/AndroidRuntime( 2886):     for parameter 2 at com.madgag.agit.views.LatestCommitView.<init>(Unknown Source)
E/AndroidRuntime( 2886):   while locating com.madgag.agit.views.LatestCommitView
E/AndroidRuntime( 2886):     for parameter 0 at com.madgag.agit.RepoSummaryAdapter.<init>(Unknown Source)
E/AndroidRuntime( 2886):   while locating com.madgag.agit.RepoSummaryAdapter
E/AndroidRuntime( 2886):     for field at com.madgag.agit.RepositoryViewerActivity.summaryAdapter(Unknown Source)
E/AndroidRuntime( 2886):   while locating com.madgag.agit.RepositoryViewerActivity
E/AndroidRuntime( 2886): Caused by: java.lang.RuntimeException: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 6cb8bc92e0ca524a76a6fa3f6814b43ea9a3b30d
E/AndroidRuntime( 2886):    at com.madgag.agit.RDTBranch$1.apply(RDTBranch.java:63)
E/AndroidRuntime( 2886):    at com.madgag.agit.RDTBranch$1.apply(RDTBranch.java:57)
E/AndroidRuntime( 2886):    at com.google.common.collect.Iterators$8.next(Iterators.java:765)
E/AndroidRuntime( 2886):    at com.google.common.collect.Lists.newArrayList(Lists.java:139)
E/AndroidRuntime( 2886):    at com.google.common.collect.Lists.newArrayList(Lists.java:119)
E/AndroidRuntime( 2886):    at com.google.common.collect.Ordering.sortedCopy(Ordering.java:511)
E/AndroidRuntime( 2886):    at com.madgag.agit.RDTBranch.getAll(RDTBranch.java:69)
E/AndroidRuntime( 2886):    at com.madgag.agit.RepoSummary.<init>(RepoSummary.java:57)
E/AndroidRuntime( 2886):    at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime( 2886):    at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
E/AndroidRuntime( 2886):    at com.google.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:81)
E/AndroidRuntime( 2886):    at com.google.inject.ConstructorInjector.construct(ConstructorInjector.java:85)
E/AndroidRuntime( 2886):    at com.google.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:111)
