### ISSUE TITLE
Eclipse Project

### ISSUE THREAD

**Issue by bodeme** [rtyley/agit#26]
Hi,

please provide a list of the needed additional source code for compiling AGIT in eclipse. I want to add some smaller features but I'm too lazy searching all that stuff.

Thanks
Markus

**Comment by rtyley** [comment]
Hi Markus, I've added some build instructions here:

https://github.com/rtyley/agit/wiki/Building-Agit

You'll need to use Maven, either from the command-line or with your IDE, to get all of Agit's dependencies. Let me know how you go!

cheers,
Roberto

**Comment by bodeme** [comment]
HI,

thank you very much. My computer is downloading some maven-files right now and I'll test IDEA tomorrow. Perhaps I switch to it, because Eclipse is a big and slow monster.

I want to add a repo browser and the possibility to save files from the repo. I hope nobody else is developing such a feature?

Markus

**Comment by bodeme** [comment]
Hi,

there's a problem with ProGuard...do you have any ideas?

 [proguard] Reading library jar [/opt/jdk1.7.0/jre/lib/rt.jar]
 [proguard] java.io.IOException: Can't read [proguard.ClassPathEntry@1fdff07](Can't process class [com/oracle/net/Sdp$1.class] %28Unsupported version number [51.0] for class format%29)
 [proguard]     at proguard.InputReader.readInput(InputReader.java:230)
 [proguard]     at proguard.InputReader.readInput(InputReader.java:200)
 [proguard]     at proguard.InputReader.readInput(InputReader.java:178)
 [proguard]     at proguard.InputReader.execute(InputReader.java:100)
 [proguard]     at proguard.ProGuard.readInput(ProGuard.java:195)
 [proguard]     at proguard.ProGuard.execute(ProGuard.java:78)
 [proguard]     at proguard.ProGuard.main(ProGuard.java:499)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Agit parent POM project ........................... SUCCESS [0.486s]
[INFO] agit test utils ................................... SUCCESS [2.198s]
[INFO] Agit - git client for Android ..................... FAILURE [12.206s]
[INFO] Agit integration tests ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.176s
[INFO] Finished at: Mon Jun 27 08:16:35 CEST 2011
[INFO] Final Memory: 34M/260M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.pyx4me:proguard-maven-plugin:2.0.4:proguard (default) on project agit: Obfuscation failed (result=1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.pyx4me:proguard-maven-plugin:2.0.4:proguard (default) on project agit: Obfuscation failed (result=1)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Obfuscation failed (result=1)
    at com.pyx4me.maven.proguard.ProGuardMojo.proguardMain(ProGuardMojo.java:633)
    at com.pyx4me.maven.proguard.ProGuardMojo.execute(ProGuardMojo.java:486)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    ... 19 more

Markus

**Comment by rtyley** [comment]
Hmm... the only thing that jumps out is that you're using jdk1.7.0, I'm currently using Sun Java 6 for my compile. This link says ProGuard doesn't support Java 7 yet:

http://sourceforge.net/projects/proguard/forums/forum/182455/topic/3889154
