### ISSUE TITLE
Crashes on Nexus 7

### ISSUE THREAD

**Issue by wrightdkevin** [rtyley/agit#86]
Crashes on Nexus 7 ever time it detects a change on the repository

**Comment by rtyley** [comment]
Hi @wrightdkevin - thanks for getting in contact, unfortunately it will be difficult for me to fix without more diagnostics - could you follow these steps to get a detailed dump of information:
- Install the Android SDK on your computer : http://developer.android.com/sdk/index.html
- Find the 'adb' executable, which should be under android-sdk/platform-tools
- Connect your phone over usb and ensure that it shows up when you execute 'adb devices'
- Start Agit, and redo the steps necessary to get the exception to happen again...
- Execute this command : adb bugreport > report.txt
- Send me the resulting report.txt file - it'll include device logs and should give me a better idea of what's going on

This issue is probably not Nexus 7-specific - I use Agit on my own Nexus 7 without problems, so the error is probably due to other factors.

**Comment by monaka** [comment]
I'm not make sure my case is same as this issue.
The git repository seems to be corrupted after "fetch canceled."
Agit is crashed by accessing corrupted git repositories.

A example of stack dump is like this. I'll send more detailed information later.

```
D/RepoListFragment(10977): Refresh requested...
D/Repos   (10977): Found 1 repos in /storage/emulated/0/git-repos
D/Repos   (10977): Found 1 repos in /storage/emulated/0/git-repos
D/ReposDataSource(10977): Found [45,/storage/emulated/0/git-repos/jgit.git]
D/ReposDataSource(10977): Found [45,/storage/emulated/0/git-repos/jgit.git]
D/ReposDataSource(10977): Found 1 repos, 0 missing repos
D/ReposDataSource(10977): Found 1 repos, 0 missing repos
I/ActivityManager(  414): Displayed com.madgag.agit/.DashboardActivity: +236ms
W/System.err(10977): java.lang.RuntimeException: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 03d50dc50b584caf2826f7db8a4748435b610f63
W/System.err(10977):    at com.madgag.agit.git.model.RDTBranch$1.apply(RDTBranch.java:83)
W/System.err(10977):    at com.madgag.agit.git.model.RDTBranch$1.apply(RDTBranch.java:77)
W/System.err(10977):    at com.google.common.collect.Iterators$8.next(Iterators.java:812)
W/System.err(10977):    at com.google.common.collect.Lists.newArrayList(Lists.java:139)
W/System.err(10977):    at com.google.common.collect.Lists.newArrayList(Lists.java:119)
W/System.err(10977):    at com.google.common.collect.Ordering.sortedCopy(Ordering.java:512)
W/System.err(10977):    at com.madgag.agit.git.model.RDTBranch.summariesForRefs(RDTBranch.java:89)
W/System.err(10977):    at com.madgag.agit.git.model.RDTBranch.getAll(RDTBranch.java:61)
W/System.err(10977):    at com.madgag.agit.RepoSummary.<init>(RepoSummary.java:73)
W/System.err(10977):    at com.madgag.agit.RepoSummary$1.apply(RepoSummary.java:47)
W/System.err(10977):    at com.madgag.agit.RepoSummary$1.apply(RepoSummary.java:42)
W/System.err(10977):    at com.google.common.base.Functions$FunctionComposition.apply(Functions.java:205)
W/System.err(10977):    at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:451)
W/System.err(10977):    at java.util.AbstractList$SimpleListIterator.next(AbstractList.java:55)
W/System.err(10977):    at com.google.common.collect.Iterators$7.computeNext(Iterators.java:648)
W/System.err(10977):    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
W/System.err(10977):    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
W/System.err(10977):    at com.google.common.collect.Lists.newArrayList(Lists.java:138)
W/System.err(10977):    at com.google.common.collect.Collections2$FilteredCollection.toArray(Collections2.java:228)
W/System.err(10977):    at java.util.ArrayList.<init>(ArrayList.java:93)
W/System.err(10977):    at com.google.common.collect.Lists.newArrayList(Lists.java:119)
W/System.err(10977):    at com.google.common.collect.Ordering.sortedCopy(Ordering.java:512)
W/System.err(10977):    at com.madgag.agit.RepoSummary.sortReposByLatestCommit(RepoSummary.java:62)
W/System.err(10977):    at com.madgag.agit.RepoListFragment$2.loadInBackground(RepoListFragment.java:87)
W/System.err(10977):    at com.madgag.agit.RepoListFragment$2.loadInBackground(RepoListFragment.java:85)
W/System.err(10977):    at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:240)
W/System.err(10977):    at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
W/System.err(10977):    at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
W/System.err(10977):    at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
W/System.err(10977):    at java.util.concurrent.FutureTask.run(FutureTask.java:234)
W/System.err(10977):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
W/System.err(10977):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
W/System.err(10977):    at java.lang.Thread.run(Thread.java:856)
W/System.err(10977): Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 03d50dc50b584caf2826f7db8a4748435b610f63
W/System.err(10977):    at org.eclipse.jgit.storage.file.WindowCursor.open(WindowCursor.java:125)
W/System.err(10977):    at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:228)
W/System.err(10977):    at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:812)
W/System.err(10977):    at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:725)
W/System.err(10977):    at com.madgag.agit.git.model.RDTBranch$1.apply(RDTBranch.java:80)
W/System.err(10977):    ... 32 more
```

**Comment by monaka** [comment]
Additional information. My phone is Galaxy Nexus / 4.2.1 build JOP40D. Factory image.

**Comment by wrightdkevin** [comment]
Thanks, that was helpful. I can now try and check the integrity of my git repo
Regards, The kevin

Masaki Muranaka notifications@github.com wrote:

> Additional information. My phone is Galaxy Nexus / 4.2.1 build JOP40D.
> Factory image.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rtyley/agit/issues/86#issuecomment-11702606

## 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.
